# Autogenerated from euler.yaml. Do not edit.

{
  description = "euler-events-hs";
  inputs = {
    # Laziness of nix allows us to be lazy here and avoid resolving deps
    # The downside is that most of this .follows are redundant
    
  };

  outputs = flakeInputs@{ self, euler-build, ... }:
    euler-build.mkEulerFlake {
      overlayPath = ./nix/overlay.nix;
      extraOverlayPaths = [
        
      ];
      mkConfig = { nixpkgs }: {
        flakeName = "euler-events-hs";
        defaultPackageName = "euler-events-hs";
        exportPackages = [
          "euler-events-hs"
        ];
        shellTools = with nixpkgs; [
          
        ];
        # shellAttrs = {
        # };
      };
      inputs = flakeInputs;
    };
}
